---
- name: Install Ansible's virt dependencies
  package:
    name:
      - python-libvirt
      - python-lxml
  become: true
- name: Record the storage pool location
  shell: |
    ~/.local/bin/vl storage_dir
  environment:
    PATH: "{{ ansible_env.PATH }}:{{ ansible_env.HOME }}/.local/bin"
  register: storage_dir

- name: Build the images
  shell: |
    cd ~/virt-lightning/images
    MIRROR_URL=http://192.168.123.1 ./image centos-7 download
  environment:
    PATH: "{{ ansible_env.PATH }}:{{ ansible_env.HOME }}/.local/bin"
  args:
    creates: "{{ storage_dir.stdout }}/upstream/centos-7.qcow2"
