---
- name: Install the virt-lightning dependencies
  package:
    name: "{{ virt_lightning_packages }}"
  become: true
- name: Install git, setup.py needs it
  package:
    name: git
  become: true
- name: Install the dependencies of the Ansible modules
  package:
    name:
      - python-libvirt
      - python-lxml
      - rsync
  become: true
- name: Start libvirt
  service:
    name: libvirtd
    state: started
  become: true

- name: Add the fine users to the current users
  user:
    name: "{{ansible_user_id}}"
    groups: "{{ virt_lightning_groups }}"
  become: true
