---
- name: Write the polkit configuration
  template:
    src: polkit.rules.j2
    dest: /etc/polkit-1/rules.d/80-libvirt.rules
  become: true
  when:
    - ansible_distribution == "Fedora"
- name: Create the pool directory
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ virt_lightning_qemu_owner }}"
    group: "{{ virt_lightning_qemu_group }}"
    mode: "0775"
  with_items:
    - /var/lib/virt-lightning/pool
    - /var/lib/virt-lightning/pool/upstream
  become: true
